huds_refresh_interval_ticks: 15
huds_high_frequency_refresh_interval_ticks: 1
money:
  enabled: true
  offset: 125
  papi_placeholder: "%vault_eco_balance_formatted%"
  worlds:
    - Surven_lobby
    - Surven_world
    - Surven_world_nether
    - Surven_world_the_end
points:
  enabled: true
  offset: 125
  papi_placeholder: "%playerpoints_points%"
  worlds:
    - Surven_lobby
    - Surven_world
    - Surven_world_nether
    - Surven_world_the_end
lang:
  hud_not_found: "&a无效的HUD!"
  wrong_usage: "&c错误的命令使用"
  destination_set: "&aDestination set."
  destination_removed: "&7Destination removed."
log:
  debug: false
