name: HUD
version: 1.0.0
main: com.peckot.hud.HUD
api-version: 1.20
depend:
  - ItemsAdder
  - PlaceholderAPI
  - PlayerPoints
  - Vault
commands:
  hud:
    description: Main plugin command.
    usage: /hud <action> <hud> [user]
permissions:
  hud.reload:
    description: Permission to use the command /hud reload to reload the plugin.
  hud.show:
    description: Permission to use the command /hud show <hud> on themselves.
  hud.hide:
    description: Permission to use the command /hud hide <hud> on themselves.
  hud.show.others:
    description: Permission to use the command /hud hide <hud> <player> on other players.
  hud.hide.others:
    description: Permission to use the command /hud hide <hud> <player> on other players.